#!/usr/bin/env python3
"""
Fix all Unicode characters in app.py to avoid encoding issues
"""

def fix_unicode_in_file():
    """Replace all Unicode characters with ASCII equivalents"""
    
    # Read the file
    with open('app.py', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Replace Unicode characters
    replacements = {
        '✅': '[OK]',
        '⚠️': '[WARNING]',
        '🎉': '[SUCCESS]',
        '🔄': '[RUNNING]',
        '📝': '[INFO]',
        '🚀': '[START]',
        '📦': '[BACKUP]',
        '⏹️': '[STOP]',
        '▶️': '[START]',
        '🌐': '[WEB]',
        '📋': '[LIST]',
        '🔍': '[CHECK]',
        '🎯': '[TARGET]',
        '📊': '[REPORT]',
        '💳': '[CARD]',
        '🏦': '[BANK]',
        '🔧': '[TOOLS]',
        '📁': '[FOLDER]',
        '🏢': '[COMPANY]',
        '📈': '[CHART]',
        '💡': '[IDEA]',
        '🔑': '[KEY]',
        '🔒': '[LOCK]',
        '📄': '[PAGE]',
        '🖨️': '[PRINT]',
        '💾': '[SAVE]',
        '🗑️': '[DELETE]',
        '✏️': '[EDIT]',
        '🔍': '[SEARCH]',
        '➕': '[PLUS]',
        '➖': '[MINUS]',
        '📤': '[UPLOAD]',
        '📥': '[DOWNLOAD]',
        '🔄': '[REFRESH]',
        '🔢': '[NUMBER]',
        '📅': '[DATE]',
        '⏰': '[TIME]',
        '📍': '[LOCATION]',
        '👥': '[USERS]',
        '👤': '[USER]',
        '🔐': '[LOGIN]',
        '🚪': '[DOOR]',
        '🏠': '[HOME]',
        '⚙️': '[SETTINGS]',
        '📱': '[PHONE]',
        '💻': '[COMPUTER]',
        '🖥️': '[MONITOR]',
        '📧': '[EMAIL]',
        '🌍': '[WORLD]',
        '🔗': '[LINK]',
        '📎': '[ATTACHMENT]',
        '📝': '[NOTE]',
        '🗒️': '[NOTEPAD]',
        '📐': '[RULER]',
        '📏': '[MEASURE]',
        '🔲': '[SQUARE]',
        '🔳': '[SQUARE]',
        '▪️': '[DOT]',
        '▫️': '[DOT]',
        '◾': '[DOT]',
        '◽': '[DOT]',
        '●': '[DOT]',
        '○': '[CIRCLE]',
        '■': '[SQUARE]',
        '□': '[SQUARE]',
        '▪': '[DOT]',
        '▫': '[DOT]',
        '▲': '[TRIANGLE]',
        '▼': '[TRIANGLE]',
        '◄': '[ARROW]',
        '►': '[ARROW]',
        '→': '[ARROW]',
        '←': '[ARROW]',
        '↑': '[ARROW]',
        '↓': '[ARROW]',
        '↔': '[ARROW]',
        '↕': '[ARROW]',
        '⇄': '[ARROW]',
        '⇅': '[ARROW]',
        '⇆': '[ARROW]',
        '⇇': '[ARROW]',
        '⇈': '[ARROW]',
        '⇉': '[ARROW]',
        '⇊': '[ARROW]',
        '⇋': '[ARROW]',
        '⇌': '[ARROW]',
        '⇐': '[ARROW]',
        '⇑': '[ARROW]',
        '⇒': '[ARROW]',
        '⇓': '[ARROW]',
        '⇔': '[ARROW]',
        '⇕': '[ARROW]',
        '⇖': '[ARROW]',
        '⇗': '[ARROW]',
        '⇘': '[ARROW]',
        '⇙': '[ARROW]',
        '↖': '[ARROW]',
        '↗': '[ARROW]',
        '↘': '[ARROW]',
        '↙': '[ARROW]',
        '↩': '[ARROW]',
        '↪': '[ARROW]',
        '↫': '[ARROW]',
        '↬': '[ARROW]',
        '↭': '[ARROW]',
        '↮': '[ARROW]',
        '↯': '[ARROW]',
        '↰': '[ARROW]',
        '↱': '[ARROW]',
        '↲': '[ARROW]',
        '↳': '[ARROW]',
        '↴': '[ARROW]',
        '↵': '[ARROW]',
        '↶': '[ARROW]',
        '↷': '[ARROW]',
        '↸': '[ARROW]',
        '↹': '[ARROW]',
        '↺': '[ARROW]',
        '↻': '[ARROW]',
        '↼': '[ARROW]',
        '↽': '[ARROW]',
        '↾': '[ARROW]',
        '↿': '[ARROW]',
        '⇀': '[ARROW]',
        '⇁': '[ARROW]',
        '⇂': '[ARROW]',
        '⇃': '[ARROW]',
        '⇄': '[ARROW]',
        '⇅': '[ARROW]',
        '⇆': '[ARROW]',
        '⇇': '[ARROW]',
        '⇈': '[ARROW]',
        '⇉': '[ARROW]',
        '⇊': '[ARROW]',
        '⇋': '[ARROW]',
        '⇌': '[ARROW]',
        '⇍': '[ARROW]',
        '⇎': '[ARROW]',
        '⇏': '[ARROW]',
        '⇐': '[ARROW]',
        '⇑': '[ARROW]',
        '⇒': '[ARROW]',
        '⇓': '[ARROW]',
        '⇔': '[ARROW]',
        '⇕': '[ARROW]',
        '⇖': '[ARROW]',
        '⇗': '[ARROW]',
        '⇘': '[ARROW]',
        '⇙': '[ARROW]',
        '↖': '[ARROW]',
        '↗': '[ARROW]',
        '↘': '[ARROW]',
        '↙': '[ARROW]',
    }
    
    # Apply replacements
    for unicode_char, ascii_replacement in replacements.items():
        content = content.replace(unicode_char, ascii_replacement)
    
    # Write the file back
    with open('app.py', 'w', encoding='utf-8') as f:
        f.write(content)
    
    print("Fixed all Unicode characters in app.py")

if __name__ == "__main__":
    fix_unicode_in_file()
